version: '3.4'
services:
  rest-api-spring:
    image: murilonerdx/rest-api-spring
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge